package:
  format-version: "1.0.0"
  name: "wireless_apps_pic32cxbz2_wbz45"
  type: "application"
  status: "production"
  required: true
  version: "1.2.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.13.0"
    - name: "dev_packs"
      type: "package"
      version: "3.13.0"
    - name: "bsp"
      type: "package"
      version: "3.13.0"
    - name: "core"
      type: "package"
      version: "3.11.0"
    - name: "crypto"
      type: "package"
      version: "3.7.4"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.3.1"
    - name: "wireless_ble"
      type: "package"
      version: "1.0.0"
    - name: "wireless_zigbee"
      type: "package"
      version: "5.0.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "1.1.0"
    - name: "wireless_system_pic32cxbz_wbz"
      type: "package"
      version: "1.2.0"
    - name: "wolfssl"
      type: "package"
      version: "4.7.0"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "1.0.0"