package:
  format-version: "1.0.0"
  name: "wireless_apps_pic32cxbz2_wbz45"
  type: "application"
  status: "production"
  required: false
  version: "v3.2.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.0"
    - name: "bsp"
      type: "package"
      version: "v3.20.0"
    - name: "core"
      type: "package"
      version: "v3.13.4"
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v11.1.0"
    - name: "wireless_ble"
      type: "package"
      version: "v1.3.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "WSGREL-49"      
    - name: "wireless_system_pic32cxbz_wbz"
      type: "package"
      version: "v1.6.0"      
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "v1.3.0"
    - name: "wireless_15_4_mac"
      type: "package"
      version: "v1.1.0-rc.1"
    - name: "wireless_zigbee"
      type: "package"
      version: "v6.1.0_release"
    - name: "wireless_thread"
      type: "package"
      version: "v1.2.0-rc.1"
    - name: "openthread"
      type: "package"
      version: "thread-reference-20230706"