package:
  format-version: "1.0.0"
  name: "wireless_apps_pic32cxbz2_wbz45"
  type: "application"
  status: "production"
  required: false
  version: "v3.1.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.2"
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
    - name: "core"
      type: "package"
      version: "v3.13.3"
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "wireless_ble"
      type: "package"
      version: "v1.1.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "Thread_Updates"      
    - name: "wireless_system_pic32cxbz_wbz"
      type: "package"
      version: "v1.5.0"      
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "v1.2.0-rc.1"
    - name: "wireless_15_4_mac"
      type: "package"
      version: "v1.0.0"
    - name: "wireless_zigbee"
      type: "package"
      version: "v5.1.1"
    - name: "wireless_thread"
      type: "package"
      version: "v1.1.0-rc.1"
    - name: "openthread"
      type: "package"
      version: "thread-reference-20230706"