/*******************************************************************************
  MAC Orphan ource

  File Name:
    mac_orphan.c
  Summary:
    Orphan scan related functionalities
  Description:
    This file implements orphan scan related functionalities on the parent side.

 *******************************************************************************/

//DOM-IGNORE-BEGIN
/*******************************************************************************
* Copyright (C) 2023 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *******************************************************************************/
//DOM-IGNORE-END

/* === Includes ============================================================ */
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include "pal.h"
#include "bmm.h"
#include "qmm.h"
#include "phy.h"
#include "ieee_mac_const.h"
#include "mac_msg_const.h"
#include "mac_api.h"
#include "mac_msg_types.h"
#include "mac_data_structures.h"
#include "stack_config.h"
#include "mac_internal.h"
#include "mac.h"
#include "mac_config.h"

/* === Macros  ============================================================= */

/* === Globals ============================================================= */

/* === Prototypes ========================================================== */

/* === Implementation ====================================================== */

#if (MAC_ORPHAN_INDICATION_RESPONSE == 1)

/**
 * @brief Handles an orphan notification
 *
 * This function processes an incoming orphan notification command.
 * A PAN coordinator gets to this function through a TAL data indication
 * message.
 *
 * @param msg Frame reception buffer
 */
void MAC_ProcessOrphanNotification(buffer_t *msg)
{
    qmm_status_t  status;
	MLME_OrphanInd_t *moi = (MLME_OrphanInd_t *)MAC_BUFFER_POINTER(msg);

	moi->cmdcode = MLME_ORPHAN_INDICATION;
	ADDR_COPY_DST_SRC_64(moi->OrphanAddress,
			macParseData.srcAddr.longAddress);

	/* Append the MLME orphan indication message to MAC-NHLE queue */
	status = qmm_queue_append(&macNhleQueue, msg);
    WPAN_PostTask();
    (void)status;
}

#endif /* MAC_ORPHAN_INDICATION_RESPONSE */

#if (MAC_ORPHAN_INDICATION_RESPONSE == 1)

/**
 * @brief Implements the MLME-ORPHAN.response
 *
 * The MLME-ORPHAN.response primitive allows the next higher layer
 * of a coordinator to respond to the MLME-ORPHAN.indication primitive.
 * The MLME-ORPHAN.response primitive is generated by the next higher
 * layer and issued to its MLME when it reaches a decision about whether
 * the orphaned device indicated in the MLME-ORPHAN.indication primitive
 * is associated.
 *
 * @param m Pointer to the message.
 */
void MAC_MLME_OrphanResponse(void *m)
{
    PHY_Retval_t pibStatus = PHY_FAILURE;
    PibValue_t pib_panid;
    PibValue_t cur_channel;
    PibValue_t cur_chpage;
    pibStatus = PHY_PibGet(macPANId, (uint8_t *)&pib_panid);

    pibStatus = PHY_PibGet(phyCurrentChannel, (uint8_t *)&cur_channel);
    pibStatus = PHY_PibGet(phyCurrentPage, (uint8_t *)&cur_chpage);
	bool transmission_status = MAC_TxCoordRealignmentCommand(
			ORPHANREALIGNMENT,
			(buffer_t *)m,
			pib_panid.pib_value_16bit,
			cur_channel.pib_value_8bit,
			cur_chpage.pib_value_8bit);

	if (!transmission_status) {
		MAC_MLME_CommStatus((uint8_t)MAC_CHANNEL_ACCESS_FAILURE,
				(buffer_t *)m);
	}
    (void)pibStatus;
}

#endif /* MAC_ORPHAN_INDICATION_RESPONSE */

/* EOF */
